name: ${PROJECT_NAME:-myproject}

services:
  nginx:
    image: ${NGINX_IMAGE:-nginx:alpine}
    container_name: ${PROJECT_NAME:-myproject}-nginx
    ports:
      - "${HTTP_PORT:-8014}:80"
      - "${HTTPS_PORT:-8015}:443"
    volumes:
      - ../public:/var/www/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - php-fpm
    restart: unless-stopped

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile.fpm
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS:-pdo_mysql,zip,gd}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${PROJECT_NAME:-myproject}-php-fpm
    volumes:
      - ../:/var/www:cached
      - ./php/php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE:-laravel}
      - DB_USERNAME=${MYSQL_USER:-laravel}
      - DB_PASSWORD=${MYSQL_PASSWORD:-laravel}
    depends_on:
      - mysql
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

  php-cli:
    build:
      context: ./php
      dockerfile: Dockerfile.cli
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS:-pdo_mysql,zip,gd}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${PROJECT_NAME:-myproject}-php-cli
    volumes:
      - ../:/var/www:cached
      - ./php/php-cli.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ~/.composer:/home/developer/.composer:cached
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE:-laravel}
      - DB_USERNAME=${MYSQL_USER:-laravel}
      - DB_PASSWORD=${MYSQL_PASSWORD:-laravel}
    depends_on:
      - mysql
    working_dir: /var/www
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    stdin_open: true
    tty: true

  mysql:
    image: ${MYSQL_IMAGE:-mysql:8.0}
    container_name: ${PROJECT_NAME:-myproject}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel}
      - MYSQL_USER=${MYSQL_USER:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-laravel}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  composer-cache:
    driver: local